server:
  tomcat:
    max-connections: 200
  port: ${port:8081}

ebookshop:
  title: E-Book Shop
  rows_per_page: 10
  file:
    filePrefix: static/uploadFile/
    staticAccessPath: /api/file/**
    #file.uploadFolder=/root/uploadFiles/
    uploadFolder: d://uploadFiles/

# ===== SpringDoc配置 =====#
springdoc:
  swagger-ui:
    # 自定义的文档界面访问路径。默认访问路径是/swagger-ui.html
    path: /springdoc/index.html

    # 字符串类型，一共三个值来控制操作和标记的默认展开设置。它可以是“list”（仅展开标记）、“full”（展开标记和操作）或“none”（不展开任何内容）。
    docExpansion: none

    # 布尔值。控制“试用”请求的请求持续时间（毫秒）的显示。
    displayRequestDuration: true

    # 布尔值。控制供应商扩展（x-）字段和操作、参数和架构值的显示。
    showExtensions: true

    # 布尔值。控制参数的扩展名（pattern、maxLength、minLength、maximum、minminimum）字段和值的显示。
    showCommonExtensions: true

    # 布尔值。禁用swagger用户界面默认petstore url。（从v1.4.1开始提供）。
    disable-swagger-default-url: true

  api-docs:
    # enabled the /v3/api-docs endpoint
    enabled: true

    # 自定义的文档api元数据访问路径。默认访问路径是/v3/api-docs
    path: /springdoc/api-docs

    # 布尔值。在@Schema（名称name、标题title和说明description，三个属性）上启用属性解析程序。
    resolve-schema-properties: true

  # 布尔值。实现OpenApi规范的打印。
  writer-with-default-pretty-printer: true

# ===== swagger配置 =====#
swagger:
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: This is E-BookShop's Spring Boot RESTful service using springdoc-openapi and OpenAPI 3.
  try-host: http://localhost:${server.port}

spring:
  application:
    name: E-Book Shop
  ## Thymeleaf
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  ## JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    name: testdb
    url: jdbc:mysql://localhost:3306/ebookshop?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
# Alibaba Druid connector pool
    druid:
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      query-timeout: 10
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      asyncInit: true
      filters: stat,wall # WebStatFilter
      web-stat-filter.enabled: true
      web-stat-filter.url-pattern: /*
      web-stat-filter.exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      web-stat-filter.session-stat-enable: true
      web-stat-filter.profile-enable: true # StatViewServlet druid
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123
        reset-enable: false
        allow:
        deny: